{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.yuua",
    "module": "journeylib",
    "version": "1055487236",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "journeylib-1055487236.jar",
          "url": "journeylib-1055487236.jar",
          "size": 84305,
          "sha512": "40b3af90dde03ca8a01354fa12bd7790fd8da0b5c6b574635d499a389874852b08963d0c0e03b785eb4ec5b2d63fd4e7d5bcb483185e427726ec6f81a47f138e",
          "sha256": "410c4a408f629e85b6f923561940adbe99bc5fdee64c9a4bc1c417aaeeb1b1ac",
          "sha1": "cf701503f37c983837c1247f977ca2f9c1ac1af4",
          "md5": "e4373e0195e2856c1559afd63790af1e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.3.0-alpha10"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "5.0.0-alpha.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.3"
          }
        },
        {
          "group": "com.jagrosh",
          "module": "jda-utilities-commons",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20211205"
          }
        },
        {
          "group": "com.sedmelluq",
          "module": "lavaplayer",
          "version": {
            "requires": "1.3.77"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "emoji-java",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "args4j",
          "module": "args4j",
          "version": {
            "requires": "2.33"
          }
        },
        {
          "group": "net.htmlparser.jericho",
          "module": "jericho-html",
          "version": {
            "requires": "3.4"
          }
        },
        {
          "group": "org.jraf",
          "module": "klibnotion",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "journeylib-1055487236.jar",
          "url": "journeylib-1055487236.jar",
          "size": 84305,
          "sha512": "40b3af90dde03ca8a01354fa12bd7790fd8da0b5c6b574635d499a389874852b08963d0c0e03b785eb4ec5b2d63fd4e7d5bcb483185e427726ec6f81a47f138e",
          "sha256": "410c4a408f629e85b6f923561940adbe99bc5fdee64c9a4bc1c417aaeeb1b1ac",
          "sha1": "cf701503f37c983837c1247f977ca2f9c1ac1af4",
          "md5": "e4373e0195e2856c1559afd63790af1e"
        }
      ]
    }
  ]
}
