{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.yuua",
    "module": "journeylib",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "journeylib-2.0.0.jar",
          "url": "journeylib-2.0.0.jar",
          "size": 169372,
          "sha512": "50a1e653956076bb8f92cb39de4b36b145e01b9eb18fc3b94a1647faf924b44ac6a8d2e3b5cdb89ce4e200cf9c66c9203ce41275b6c044cf69bd6aa9535f3e49",
          "sha256": "f5087b9930f805c72c1ac59dea11c57f13c20695fec1617631e0a1683c965d07",
          "sha1": "135621de53a9116632b34d395978f6551179dc26",
          "md5": "cb39c764cd7645a0f29727b2b4b87620"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "5.0.0-alpha.9"
          }
        },
        {
          "group": "com.github.minndevelopment",
          "module": "jda-ktx",
          "version": {
            "requires": "9f01b74"
          }
        },
        {
          "group": "com.jagrosh",
          "module": "jda-utilities-commons",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.sedmelluq",
          "module": "lavaplayer",
          "version": {
            "requires": "1.3.77"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "emoji-java",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.3.0-alpha14"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20211205"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "args4j",
          "module": "args4j",
          "version": {
            "requires": "2.33"
          }
        },
        {
          "group": "net.htmlparser.jericho",
          "module": "jericho-html",
          "version": {
            "requires": "3.4"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.5"
          }
        },
        {
          "group": "org.jraf",
          "module": "klibnotion",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "journeylib-2.0.0.jar",
          "url": "journeylib-2.0.0.jar",
          "size": 169372,
          "sha512": "50a1e653956076bb8f92cb39de4b36b145e01b9eb18fc3b94a1647faf924b44ac6a8d2e3b5cdb89ce4e200cf9c66c9203ce41275b6c044cf69bd6aa9535f3e49",
          "sha256": "f5087b9930f805c72c1ac59dea11c57f13c20695fec1617631e0a1683c965d07",
          "sha1": "135621de53a9116632b34d395978f6551179dc26",
          "md5": "cb39c764cd7645a0f29727b2b4b87620"
        }
      ]
    }
  ]
}
