{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.yuua",
    "module": "journeylib",
    "version": "0.3.7-renovate-com-squareup-okhttp3-okhttp-5-x.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "journeylib-0.3.7-renovate-com-squareup-okhttp3-okhttp-5-x.0.jar",
          "url": "journeylib-0.3.7-renovate-com-squareup-okhttp3-okhttp-5-x.0.jar",
          "size": 98785,
          "sha512": "263b22c9903db6246a358ae652be310df6264b7deab368ec047b86726772db84fde6abf46752a97029b6f034be59e0f171c9b2d8b08d9e1e75cc8aa295f61fe2",
          "sha256": "19749aad5bb93f09f5538deb2309b10f59211e7399a5f388d4cce553b10c0e7e",
          "sha1": "0df37bf850978f80f9f1c296db1957100503eace",
          "md5": "7bca0935b666133ff0713e0b42e4c84a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.3.0-alpha10"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "5.0.0-alpha.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.5"
          }
        },
        {
          "group": "com.jagrosh",
          "module": "jda-utilities-commons",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20211205"
          }
        },
        {
          "group": "com.sedmelluq",
          "module": "lavaplayer",
          "version": {
            "requires": "1.3.77"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "emoji-java",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "args4j",
          "module": "args4j",
          "version": {
            "requires": "2.33"
          }
        },
        {
          "group": "net.htmlparser.jericho",
          "module": "jericho-html",
          "version": {
            "requires": "3.4"
          }
        },
        {
          "group": "org.jraf",
          "module": "klibnotion",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "journeylib-0.3.7-renovate-com-squareup-okhttp3-okhttp-5-x.0.jar",
          "url": "journeylib-0.3.7-renovate-com-squareup-okhttp3-okhttp-5-x.0.jar",
          "size": 98785,
          "sha512": "263b22c9903db6246a358ae652be310df6264b7deab368ec047b86726772db84fde6abf46752a97029b6f034be59e0f171c9b2d8b08d9e1e75cc8aa295f61fe2",
          "sha256": "19749aad5bb93f09f5538deb2309b10f59211e7399a5f388d4cce553b10c0e7e",
          "sha1": "0df37bf850978f80f9f1c296db1957100503eace",
          "md5": "7bca0935b666133ff0713e0b42e4c84a"
        }
      ]
    }
  ]
}
