{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.yuua",
    "module": "journeylib",
    "version": "1181975226",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "journeylib-1181975226.jar",
          "url": "journeylib-1181975226.jar",
          "size": 30340,
          "sha512": "94b8286fb57d35ae06f2e99ffa71628c78dafbcd0a39f51c6b9152f85fad8243b0d50df62e8c16e005410570e168a8d0734aebd8ad1e2f48adc3f67bdd8c3a2f",
          "sha256": "9259222823a12d0b16b49d7e2cf8d54a75a6960a4c97a59bd8c7c0b7378b442a",
          "sha1": "a49cd99fb10737e18ad06335d802a1c3d91892f3",
          "md5": "25b14301ef5f83812fd0f79ada4a5aa9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.3.0-alpha10"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "5.0.0-alpha.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.3"
          }
        },
        {
          "group": "com.jagrosh",
          "module": "jda-utilities-commons",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20211205"
          }
        },
        {
          "group": "com.sedmelluq",
          "module": "lavaplayer",
          "version": {
            "requires": "1.3.77"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "emoji-java",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "args4j",
          "module": "args4j",
          "version": {
            "requires": "2.33"
          }
        },
        {
          "group": "net.htmlparser.jericho",
          "module": "jericho-html",
          "version": {
            "requires": "3.4"
          }
        },
        {
          "group": "org.jraf",
          "module": "klibnotion",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "journeylib-1181975226.jar",
          "url": "journeylib-1181975226.jar",
          "size": 30340,
          "sha512": "94b8286fb57d35ae06f2e99ffa71628c78dafbcd0a39f51c6b9152f85fad8243b0d50df62e8c16e005410570e168a8d0734aebd8ad1e2f48adc3f67bdd8c3a2f",
          "sha256": "9259222823a12d0b16b49d7e2cf8d54a75a6960a4c97a59bd8c7c0b7378b442a",
          "sha1": "a49cd99fb10737e18ad06335d802a1c3d91892f3",
          "md5": "25b14301ef5f83812fd0f79ada4a5aa9"
        }
      ]
    }
  ]
}
