{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.yuua",
    "module": "journeylib",
    "version": "2.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "journeylib-2.8.6.jar",
          "url": "journeylib-2.8.6.jar",
          "size": 174498,
          "sha512": "02b682ed22805abc17ba4f781f43eea811561702164e76cac0a69fbbbf50e758dc2c742315388f7de6d20a9f73b74649bff5430501cdf48aa823e1299a83d7a8",
          "sha256": "0eabb87262a49e138d20a36ff29fc6e9e13cca0c01c3abd5b832ac77d1aa79f5",
          "sha1": "3515fd3db86849d97a09299b790b3cefe5d0b25a",
          "md5": "5f06b09f838e93ed014fb789c1d6a73b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "5.0.0-alpha.9"
          }
        },
        {
          "group": "com.github.minndevelopment",
          "module": "jda-ktx",
          "version": {
            "requires": "9f01b74"
          }
        },
        {
          "group": "com.jagrosh",
          "module": "jda-utilities-commons",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "com.sedmelluq",
          "module": "lavaplayer",
          "version": {
            "requires": "1.3.77"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "emoji-java",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.3.0-alpha14"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20211205"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "args4j",
          "module": "args4j",
          "version": {
            "requires": "2.33"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.reflections",
          "module": "reflections",
          "version": {
            "requires": "0.10.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.5"
          }
        },
        {
          "group": "org.jraf",
          "module": "klibnotion",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "journeylib-2.8.6.jar",
          "url": "journeylib-2.8.6.jar",
          "size": 174498,
          "sha512": "02b682ed22805abc17ba4f781f43eea811561702164e76cac0a69fbbbf50e758dc2c742315388f7de6d20a9f73b74649bff5430501cdf48aa823e1299a83d7a8",
          "sha256": "0eabb87262a49e138d20a36ff29fc6e9e13cca0c01c3abd5b832ac77d1aa79f5",
          "sha1": "3515fd3db86849d97a09299b790b3cefe5d0b25a",
          "md5": "5f06b09f838e93ed014fb789c1d6a73b"
        }
      ]
    }
  ]
}
