{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.yuua",
    "module": "journeylib",
    "version": "0.3.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "journeylib-0.3.9.jar",
          "url": "journeylib-0.3.9.jar",
          "size": 98785,
          "sha512": "3ff7a6cb03c379b8e77c38557c6f40e4ccc7a090d4e2d64fd87ca7797f67298014f187bb5d2b2c425c42661bb1830072bffb71bd597cbe2419a2413ef94bff5a",
          "sha256": "1b62f5042eeaa9d213748da95815c1b353bd905d1b5028e236afbf3d06497b90",
          "sha1": "9f98f3f3cbe2b0c59cd1add17771ff1099ea0fd9",
          "md5": "574d2dbdaed646454a6bd856165dcf75"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ch.qos.logback",
          "module": "logback-classic",
          "version": {
            "requires": "1.3.0-alpha10"
          }
        },
        {
          "group": "net.dv8tion",
          "module": "JDA",
          "version": {
            "requires": "5.0.0-alpha.2"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.0.0-alpha.5"
          }
        },
        {
          "group": "com.jagrosh",
          "module": "jda-utilities-commons",
          "version": {
            "requires": "3.1.0"
          }
        },
        {
          "group": "org.json",
          "module": "json",
          "version": {
            "requires": "20211205"
          }
        },
        {
          "group": "com.sedmelluq",
          "module": "lavaplayer",
          "version": {
            "requires": "1.3.77"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "com.vdurmont",
          "module": "emoji-java",
          "version": {
            "requires": "5.1.1"
          }
        },
        {
          "group": "args4j",
          "module": "args4j",
          "version": {
            "requires": "2.33"
          }
        },
        {
          "group": "net.htmlparser.jericho",
          "module": "jericho-html",
          "version": {
            "requires": "3.4"
          }
        },
        {
          "group": "org.jraf",
          "module": "klibnotion",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "journeylib-0.3.9.jar",
          "url": "journeylib-0.3.9.jar",
          "size": 98785,
          "sha512": "3ff7a6cb03c379b8e77c38557c6f40e4ccc7a090d4e2d64fd87ca7797f67298014f187bb5d2b2c425c42661bb1830072bffb71bd597cbe2419a2413ef94bff5a",
          "sha256": "1b62f5042eeaa9d213748da95815c1b353bd905d1b5028e236afbf3d06497b90",
          "sha1": "9f98f3f3cbe2b0c59cd1add17771ff1099ea0fd9",
          "md5": "574d2dbdaed646454a6bd856165dcf75"
        }
      ]
    }
  ]
}
